  version: '3.7'

  services:
    db:
      image: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_PASSWORD
    web:
      build: .
      volumes:
        - ./:/app
      ports:
        - "8000:8000"
      depends_on:
        - db
