# Generated by Django 2.2.5 on 2020-03-04 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motorhome', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Подія', 'verbose_name_plural': 'Події'},
        ),
    ]
