# Generated by Django 2.2.5 on 2020-03-05 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motorhome', '0002_auto_20200305_0138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name_plural': 'Пропозиції'},
        ),
    ]
