# Generated by Django 2.2.5 on 2020-03-05 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motorhome', '0003_auto_20200305_1050'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Подія',
        ),
        migrations.RenameModel(
            old_name='Choice',
            new_name='Пропозиція',
        ),
    ]
