# Generated by Django 2.2.5 on 2020-03-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorhome', '0004_auto_20200305_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='подія',
            old_name='question_text',
            new_name='action_text',
        ),
        migrations.AddField(
            model_name='подія',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Додаткова інформація'),
        ),
        migrations.DeleteModel(
            name='Пропозиція',
        ),
    ]
