# Generated by Django 2.2.5 on 2020-03-05 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motorhome', '0006_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профіль замовника', 'verbose_name_plural': 'Профілі замовників'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='car_model',
            field=models.CharField(blank=True, max_length=30, verbose_name='Модель авто'),
        ),
        migrations.AddField(
            model_name='profile',
            name='prod_year',
            field=models.CharField(blank=True, max_length=30, verbose_name='Рік виробництва'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Замовник'),
        ),
    ]
