# Generated by Django 2.2.5 on 2020-03-05 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motorhome', '0007_auto_20200305_2316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профіль користувача', 'verbose_name_plural': 'Профілі користувачів'},
        ),
    ]
