# Generated by Django 2.2.5 on 2020-03-07 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motorhome', '0008_auto_20200306_0005'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Подія',
            new_name='Event',
        ),
    ]
